// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MangaWorkflow.Entities.HuyNQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace MangaWorkflow.Repositories.HuyNQ.DBContext;

public partial class MangaWorkflowContext : DbContext
{
    public MangaWorkflowContext()
    {
    }

    public MangaWorkflowContext(DbContextOptions<MangaWorkflowContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChapterHuyNq> ChapterHuyNqs { get; set; }

    public virtual DbSet<ChapterMetaHuyNq> ChapterMetaHuyNqs { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //    => optionsBuilder.UseSqlServer("Data Source=DESKTOP-HF5MGJA\\HUYNGUYEN;Initial Catalog=MangaWorkflow;Persist Security Info=True;User ID=sa;Password=12345");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChapterHuyNq>(entity =>
        {
            entity.HasKey(e => e.HuynqId).HasName("PK__Chapter__745EFE8769DFFE96");

            entity.ToTable("ChapterHuyNQ");

            entity.Property(e => e.HuynqId)
                .UseIdentityColumn()
                .HasColumnName("huynq_id");
            entity.Property(e => e.Approved).HasColumnName("approved");
            entity.Property(e => e.ChapterMetaHuynqId).HasColumnName("chapter_meta_huynq_id");
            entity.Property(e => e.ChapterNumber).HasColumnName("chapter_number");
            entity.Property(e => e.EditorComment)
                .HasColumnType("text")
                .HasColumnName("editor_comment");
            entity.Property(e => e.LayoutVersion)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("layout_version");
            entity.Property(e => e.PageCount).HasColumnName("page_count");
            entity.Property(e => e.PriorityLevel).HasColumnName("priority_level");
            entity.Property(e => e.ReleaseDate)
                .HasColumnType("datetime")
                .HasColumnName("release_date");
            entity.Property(e => e.ReviewNotes)
                .HasColumnType("text")
                .HasColumnName("review_notes");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("title");

            entity.HasOne(d => d.ChapterMetaHuynq).WithMany(p => p.ChapterHuyNqs)
                .HasForeignKey(d => d.ChapterMetaHuynqId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_chapter_meta");
        });

        modelBuilder.Entity<ChapterMetaHuyNq>(entity =>
        {
            entity.HasKey(e => e.HuynqId).HasName("PK__ChapterM__1F8299A076B370B8");

            entity.ToTable("ChapterMetaHuyNQ");

            entity.Property(e => e.HuynqId)
                .ValueGeneratedNever()
                .HasColumnName("huynq_id");
            entity.Property(e => e.Code)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}