// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace MangaWorkflow.SoapService.HuyNQ.SoapModels;

[DataContract]
public partial class ChapterHuyNq
{
    [Key]
    [DataMember]
    public int HuynqId { get; set; }

    [DataMember]
    public int? ChapterMetaHuynqId { get; set; }

    [DataMember]
    public string Title { get; set; }

    [DataMember]
    public int? ChapterNumber { get; set; }

    [DataMember]
    public int? PageCount { get; set; }

    [DataMember]
    public bool? Approved { get; set; }

    [DataMember]
    public DateTime? ReleaseDate { get; set; }

    [DataMember]
    public int? PriorityLevel { get; set; }

    [DataMember]
    public string EditorComment { get; set; }

    [DataMember]
    public string LayoutVersion { get; set; }

    [DataMember]
    public string ReviewNotes { get; set; }

    // public virtual ChapterMetaHuyNq ChapterMetaHuynq { get; set; }
}
