// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace MangaWorkflow.SoapService.HuyNQ.SoapModels;

[DataContract]
public partial class ChapterMetaHuyNq
{
    [DataMember]
    public int HuynqId { get; set; }

    [DataMember]
    public string Code { get; set; }

    [DataMember]
    public string Description { get; set; }

    // public virtual ICollection<ChapterHuyNq> ChapterHuyNqs { get; set; } = new List<ChapterHuyNq>();
}
